version: '2'
services:

  python-microservice:
    build:
      context: ./microservices/python/
      dockerfile: Dockerfile
    volumes_from :
      - source_base
    ports:
     - "8761:8761"
    tty: true

  r-microservice:
    build:
      context: ./microservices/r/
      dockerfile: Dockerfile
    volumes_from :
      - source_base
    ports:
     - "8762:8762"
    tty: true


  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    volumes_from:
      - source_base1
  spark-worker-1:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
  spark-worker-2:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker1"


  ##
  # Source containers
  ##
  source_base:
        image: nginx:stable
        volumes:
            - ../source:/var/www/html
        command: "true"

  source_base1:
        image: nginx:stable
        volumes:
            - ../source/realtime-engine:/var/www/html
